### ISSUE TITLE
生成的 docx 文档有试用版水印，且在命令行运行时有异常

### ISSUE THREAD

**Issue by Emrys365** [fengdongdongwsn/PdfTool#11]
### 环境
+ macOS Catalina, Version 10.15.7
+ PDF 文件为通过 Markdown 生成的中英文混杂的 PDF

<details><summary>以下是我在命令行界面操作的步骤：</summary><div>

```bash
> java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

> git clone https://github.com/fengdongdongwsn/PdfTool.git
> cd PdfTool
> cat > src/Main.java << 'EOF'
import java.io.File;

public class Main {
	public static void main(String[] args) {
		if (args.length == 1) {
			String path = args[0];

			// 检查文件是否存在
			File f = new File(path);
			if (f.exists() && !f.isDirectory()) {
				String res = new PdfToWord().pdftoword(path);
				System.out.println("\n" + path + "\n -> " + res);
			} else {
				System.out.println("错误：文件 '" + path + "' 不存在");
			}

		} else {
			System.out.println("请传入一个 PDF 文件的路径！");
		}
	}
}
EOF

> javac -classpath lib/Spire.Doc.jar:lib/Spire.Pdf.jar src/*.java -d bin/

> java -cp bin:lib/Spire.Doc.jar:lib/Spire.Pdf.jar Main ./python_note.pdf

./doc/
java.lang.IllegalStateException: Cannot find table 'OS/2' in the font file.
	at com.spire.doc.packages.sprmUA.spr  (Unknown Source)
	at com.spire.doc.packages.spraWA.spr  (Unknown Source)
	at com.spire.doc.packages.spraWA.spr  (Unknown Source)
	at com.spire.doc.packages.spraWA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprZOc.<init>(Unknown Source)
	at com.spire.doc.packages.sprUSc.spr (Unknown Source)
	at com.spire.doc.packages.sprUSc.spr  (Unknown Source)
	at com.spire.doc.packages.sprUSc.spr  (Unknown Source)
	at com.spire.doc.packages.spryRc.spr (Unknown Source)
	at com.spire.doc.packages.sprRRc.spr (Unknown Source)
	at com.spire.doc.packages.sprRRc.spr  (Unknown Source)
	at com.spire.doc.packages.sprRRc.spr  (Unknown Source)
	at com.spire.doc.packages.sprRRc.spr  (Unknown Source)
	at com.spire.doc.Document.spr   (Unknown Source)
	at com.spire.doc.Document.saveToFile(Unknown Source)
	at com.spire.doc.Document.saveToFile(Unknown Source)
	at MergeWordDocument.merge(MergeWordDocument.java:24)
	at PdfToWord.pdftoword(PdfToWord.java:64)
	at Main.main(Main.java:12)
java.lang.IllegalStateException: Cannot find table 'OS/2' in the font file.
	at com.spire.doc.packages.sprmUA.spr  (Unknown Source)
	at com.spire.doc.packages.spraWA.spr  (Unknown Source)
	at com.spire.doc.packages.spraWA.spr  (Unknown Source)
	at com.spire.doc.packages.spraWA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprZOc.<init>(Unknown Source)
	at com.spire.doc.packages.sprUSc.spr (Unknown Source)
	at com.spire.doc.packages.sprUSc.spr  (Unknown Source)
	at com.spire.doc.packages.sprUSc.spr  (Unknown Source)
	at com.spire.doc.packages.spryRc.spr (Unknown Source)
	at com.spire.doc.packages.sprRRc.spr (Unknown Source)
	at com.spire.doc.packages.sprRRc.spr  (Unknown Source)
	at com.spire.doc.packages.sprRRc.spr  (Unknown Source)
	at com.spire.doc.packages.sprRRc.spr  (Unknown Source)
	at com.spire.doc.Document.spr   (Unknown Source)
	at com.spire.doc.Document.saveToFile(Unknown Source)
	at com.spire.doc.Document.saveToFile(Unknown Source)
	at MergeWordDocument.merge(MergeWordDocument.java:24)
	at PdfToWord.pdftoword(PdfToWord.java:64)
	at Main.main(Main.java:12)
java.lang.IllegalStateException: Cannot find table 'OS/2' in the font file.
	at com.spire.doc.packages.sprmUA.spr  (Unknown Source)
	at com.spire.doc.packages.spraWA.spr  (Unknown Source)
	at com.spire.doc.packages.spraWA.spr  (Unknown Source)
	at com.spire.doc.packages.spraWA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprtUA.spr  (Unknown Source)
	at com.spire.doc.packages.sprZOc.<init>(Unknown Source)
	at com.spire.doc.packages.sprUSc.spr (Unknown Source)
	at com.spire.doc.packages.sprUSc.spr  (Unknown Source)
	at com.spire.doc.packages.sprUSc.spr  (Unknown Source)
	at com.spire.doc.packages.spryRc.spr (Unknown Source)
	at com.spire.doc.packages.sprRRc.spr (Unknown Source)
	at com.spire.doc.packages.sprRRc.spr  (Unknown Source)
	at com.spire.doc.packages.sprRRc.spr  (Unknown Source)
	at com.spire.doc.packages.sprRRc.spr  (Unknown Source)
	at com.spire.doc.Document.spr   (Unknown Source)
	at com.spire.doc.Document.saveToFile(Unknown Source)
	at com.spire.doc.Document.saveToFile(Unknown Source)
	at MergeWordDocument.merge(MergeWordDocument.java:24)
	at PdfToWord.pdftoword(PdfToWord.java:64)
	at Main.main(Main.java:12)
true

./python.pdf
 -> 转换成功
```

</div></details>

### 问题
**一、执行命令** `java -cp bin:lib/Spire.Doc.jar:lib/Spire.Pdf.jar Main ./python_note.pdf` **的过程中出现了一些异常：**
```
java.lang.IllegalStateException: Cannot find table 'OS/2' in the font file.
```
详细报错见最上面的折叠部分。

**二、生成的 docx 文档存在水印**
生成的 docx 文档如下：
![demo](https://user-images.githubusercontent.com/18532145/103782183-1a241c00-5072-11eb-8893-063d7714a7bc.png)

水印内容为 `Evaluation Warning : The document was   created with Spire.PDF for Java.`

这些水印能不能不生成，或者自动删除？

**Comment by dave0824** [comment]
您好，请问这个问题您解决了嘛，我这遇到了同样的问题

**Comment by nocb** [comment]
同问

**Comment by Emrys365** [comment]
@dave0824 @nocb 
抱歉之前没看到，目前解决了运行时字体相关报错的问题，和 https://github.com/fengdongdongwsn/PdfTool/issues/10#issuecomment-755320547 这里的原因差不多，需要在 [src/PdfToWord.java#L33](https://github.com/fengdongdongwsn/PdfTool/blob/master/src/PdfToWord.java#L33) 这一行之前设置中文的 Locale，然后就不会在处理含中文字符的 PDF 时出现前面说的字体报错了。

```java
import java.io.File;
import java.util.Locale;
...
            if (flag && flag1) {
                // 0、将语言设置为中文，以处理 PDF 中可能存在的中文字符
                Locale locale = new Locale("zh", "CN");
                Locale.setDefault(locale);

                // 1、加载pdf
                PdfDocument pdf = new PdfDocument();
...
```

试用版水印目前没有找到办法去除，但这个水印在生成的 docx 文档里面比较容易去除，所以暂时没去管这个问题。

**Comment by zuzuviewer** [comment]
用office生成的没有水印了，可以看下我写的
[pdf转word](https://github.com/zuzuviewer/dolks)
我的项目也是从这个项目借鉴的，但是自己解决了遇到的一些问题，包括你这个
