### ISSUE TITLE
代码jar证书有问题啊

### ISSUE THREAD

**Issue by iSummerRain** [fengdongdongwsn/PdfTool#7]
Exception in thread "main" java.lang.NoSuchMethodError: com.spire.license.LicenseProvider.validateVarAndGetInfo(Ljava/lang/String;)Lcom/spire/license/Assembly;
	at com.spire.doc.Document.spr  (Unknown Source)
	at com.spire.doc.Document.<init>(Unknown Source)
	at com.spire.doc.Document.<init>(Unknown Source)

**Comment by hkenter** [comment]
将lib内jar包引用，maven改为provide不参与编译即可
